version: '3'
services:


  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: dev
      VIRTUAL_HOST: admin.kevinbpalmer.com

volumes:
    db_data:

networks:
  default:
    external:
      name: nginx-proxy
