version: '3'
services:


  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: dev
      VIRTUAL_HOST: admin.kevinbpalmer.com

  backup:
    image: jswetzen/mysql-backup
    container_name: backup
    depends_on:
      - mysql
    volumes:
        - ./mysql-backup:/backup
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASS: dev
      CRON_TIME: '0 */6 * * *'
      MAX_BACKUPS: 30
      INIT_BACKUP: 'true'
    restart: always

volumes:
    db_data:

networks:
  default:
    external:
      name: nginx-proxy
