version: '3'

services:

  demo-site:
    image: kbpalmer/jlb-wordpress:4.8.3-php7.1
    container_name: demo-site
    depends_on:
      - db
    restart: always
    volumes:
      - ./sites/demo-site:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_PASSWORD: dev
      WORDPRESS_DB_NAME: demo-site
      VIRTUAL_HOST: demo.kevinbpalmer.com

  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: dev


  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: dev

volumes:
    db_data:

networks:
  default:
    external:
      name: nginx-proxy
